-- begin RATLAB_LABORATORY
create unique index IDX_RATLAB_LABORATORY_UK_CODE on RATLAB_LABORATORY (CODE) where DELETE_TS is null ^
create unique index IDX_RATLAB_LABORATORY_UK_TITLE on RATLAB_LABORATORY (TITLE) where DELETE_TS is null ^
create unique index IDX_RATLAB_LABORATORY_UK_DAY_END on RATLAB_LABORATORY (DAY_END) where DELETE_TS is null ^
-- end RATLAB_LABORATORY
-- begin RATLAB_CERTIFICATE
alter table RATLAB_CERTIFICATE add constraint FK_RATLAB_CERTIFICATE_ON_OWNER foreign key (OWNER_ID) references RATLAB_EMPLOYEE(ID)^
create unique index IDX_RATLAB_CERTIFICATE_UK_CODE on RATLAB_CERTIFICATE (CODE) where DELETE_TS is null ^
create index IDX_RATLAB_CERTIFICATE_ON_OWNER on RATLAB_CERTIFICATE (OWNER_ID)^
-- end RATLAB_CERTIFICATE
-- begin RATLAB_EMPLOYEE
alter table RATLAB_EMPLOYEE add constraint FK_RATLAB_EMPLOYEE_ON_LABORATORY foreign key (LABORATORY_ID) references RATLAB_LABORATORY(ID)^
alter table RATLAB_EMPLOYEE add constraint FK_RATLAB_EMPLOYEE_ON_SUPERVISOR foreign key (SUPERVISOR_ID) references RATLAB_EMPLOYEE(ID)^
create index IDX_RATLAB_EMPLOYEE_ON_LABORATORY on RATLAB_EMPLOYEE (LABORATORY_ID)^
create index IDX_RATLAB_EMPLOYEE_ON_SUPERVISOR on RATLAB_EMPLOYEE (SUPERVISOR_ID)^
-- end RATLAB_EMPLOYEE
-- begin RATLAB_EMPLOYEE_RESEARCH_LINK
alter table RATLAB_EMPLOYEE_RESEARCH_LINK add constraint FK_EMPRES_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references RATLAB_EMPLOYEE(ID)^
alter table RATLAB_EMPLOYEE_RESEARCH_LINK add constraint FK_EMPRES_ON_RESEARCH foreign key (RESEARCH_ID) references RATLAB_RESEARCH(ID)^
-- end RATLAB_EMPLOYEE_RESEARCH_LINK
-- begin RATLAB_RESOURCE_REQUIREMENT
alter table RATLAB_RESOURCE_REQUIREMENT add constraint FK_RATLAB_RESOURCE_REQUIREMENT_ON_RESOURCE foreign key (RESOURCE_ID) references RATLAB_MISC_RESOURCE(ID)^
alter table RATLAB_RESOURCE_REQUIREMENT add constraint FK_RATLAB_RESOURCE_REQUIREMENT_ON_RESEARCH foreign key (RESEARCH_ID) references RATLAB_RESEARCH(ID)^
create index IDX_RATLAB_RESOURCE_REQUIREMENT_ON_RESOURCE on RATLAB_RESOURCE_REQUIREMENT (RESOURCE_ID)^
create index IDX_RATLAB_RESOURCE_REQUIREMENT_ON_RESEARCH on RATLAB_RESOURCE_REQUIREMENT (RESEARCH_ID)^
-- end RATLAB_RESOURCE_REQUIREMENT
