alter table RATLAB_CERTIFICATE add constraint FK_RATLAB_CERTIFICATE_ON_OWNER foreign key (OWNER_ID) references RATLAB_EMPLOYEE(ID);
create unique index IDX_RATLAB_CERTIFICATE_UK_CODE on RATLAB_CERTIFICATE (CODE) where DELETE_TS is null ;
create index IDX_RATLAB_CERTIFICATE_ON_OWNER on RATLAB_CERTIFICATE (OWNER_ID);
