alter table RATLAB_EMPLOYEE add constraint FK_RATLAB_EMPLOYEE_ON_LABORATORY foreign key (LABORATORY_ID) references RATLAB_LABORATORY(ID);
alter table RATLAB_EMPLOYEE add constraint FK_RATLAB_EMPLOYEE_ON_SUPERVISOR foreign key (SUPERVISOR_ID) references RATLAB_EMPLOYEE(ID);
create index IDX_RATLAB_EMPLOYEE_ON_LABORATORY on RATLAB_EMPLOYEE (LABORATORY_ID);
create index IDX_RATLAB_EMPLOYEE_ON_SUPERVISOR on RATLAB_EMPLOYEE (SUPERVISOR_ID);
